import {
  assertValidToolManifest,
  type PlatformToolManifest,
} from '@/lib/ai/tools/platform/contracts'
import { STANDARD_PLATFORM_TOOL_ERRORS } from '@/lib/services/platform/tool-contract-defaults'

export const SERVICES_TOOL_MANIFESTS: readonly PlatformToolManifest[] = [
  assertValidToolManifest({
    key: 'services.search',
    version: 1,
    domain: 'services',
    title: 'Search services',
    description:
      'Search the active services catalog. Returns name + public description + code.',
    purpose: 'Find active catalog services relevant to a request.',
    whenToUse: ['The user needs to discover which configured service may fit their need.'],
    whenNotToUse: ['Do not use it to create, edit, price, or activate a service.'],
    inputSchema: {
      query: { type: 'string', description: 'Free-text query; matches against name and code.', required: false },
      category_id: { type: 'string', description: 'Restrict to a specific category UUID.', required: false },
      limit: { type: 'number', description: 'Max results. Default 10, max 50.', required: false },
    },
    outputSchema: { description: 'Array<{ id, name, code, category_id, public_description }>' },
    permission: 'read',
    risk: 'read',
    allowedPlanes: ['customer', 'admin'],
    requiredCapabilities: ['services.read'],
    supportedGrantConstraints: ['channels'],
    sideEffect: 'none',
    approvalRequired: false,
    idempotent: true,
    audit: 'invocation',
    modelExposed: true,
    serverOnly: false,
    examples: [],
    errorContract: STANDARD_PLATFORM_TOOL_ERRORS,
  }),
  assertValidToolManifest({
    key: 'services.get',
    version: 1,
    domain: 'services',
    title: 'Read service',
    description: 'Read a single service by id or code. Returns public fields only.',
    purpose: 'Read one configured service using model-safe fields.',
    whenToUse: ['A service id/code is known and its current public/AI-safe details are needed.'],
    whenNotToUse: ['Do not infer internal fields or use the result as authority to mutate the catalog.'],
    inputSchema: {
      id_or_code: { type: 'string', description: 'Service UUID or internal code (e.g. COV-SANA-CASH).', required: true },
    },
    outputSchema: { description: '{ id, name, code, status, public_description, field_values, pricing_quote }' },
    permission: 'read',
    risk: 'read',
    allowedPlanes: ['customer', 'admin'],
    requiredCapabilities: ['services.read'],
    supportedGrantConstraints: ['channels'],
    sideEffect: 'none',
    approvalRequired: false,
    idempotent: true,
    audit: 'invocation',
    modelExposed: true,
    serverOnly: false,
    examples: [],
    errorContract: STANDARD_PLATFORM_TOOL_ERRORS,
  }),
  assertValidToolManifest({
    key: 'services.match_request',
    version: 1,
    domain: 'services',
    title: 'Match service request',
    description:
      'Match a customer request against equipped service schemas. Returns exact / partial / none with missing fields. NEVER prices or promises on "none" — escalate instead.',
    purpose: 'Classify a request against configured service schemas.',
    whenToUse: ['The conversation describes a service need but the exact configured service is not yet known.'],
    whenNotToUse: ['Do not promise a service when the match is none or required fields are missing.'],
    inputSchema: {
      service_hint: { type: 'string', description: 'What the customer asked for, in a few words.', required: false },
      attributes: { type: 'object', description: 'What the agent understood from the customer, as key/value pairs.', required: true },
      limit: { type: 'number', description: 'Max candidates. Default 10, max 50.', required: false },
    },
    outputSchema: { description: 'MatchResult { match: exact|partial|none, candidates: [{ service_id, name, classification, missing_fields, unknown_fields }] }' },
    permission: 'read',
    risk: 'read',
    allowedPlanes: ['customer', 'admin'],
    requiredCapabilities: ['services.read'],
    supportedGrantConstraints: ['channels'],
    sideEffect: 'none',
    approvalRequired: false,
    idempotent: true,
    audit: 'invocation',
    modelExposed: true,
    serverOnly: false,
    examples: [],
    errorContract: STANDARD_PLATFORM_TOOL_ERRORS,
  }),
  assertValidToolManifest({
    key: 'services.propose_update',
    version: 1,
    domain: 'services',
    title: 'Propose service update',
    description:
      'Admin-only proposal to publish a new service revision. Internal-only fields are preserved but never exposed to or editable by the model.',
    purpose: 'Create a typed, reviewable proposal for a service revision.',
    whenToUse: ['A trusted administrator explicitly asks to change allowed service data.'],
    whenNotToUse: ['Never use for a customer request or to edit internal-only fields outside the typed schema.'],
    inputSchema: {
      service_id: { type: 'string', description: 'Service UUID.', required: true },
      name: { type: 'string', description: 'Optional new service name.', required: false },
      public_description: { type: 'string', description: 'Optional new public description.', required: false },
      ai_guidance: { type: 'string', description: 'Optional AI guidance. Never customer-visible.', required: false },
      field_values_patch: { type: 'object', description: 'Patch to non-internal schema fields only.', required: false },
      pricing_rule_id: { type: 'string', description: 'Optional published pricing-rule UUID.', required: false },
      status: { type: 'enum', description: 'Optional service lifecycle state.', values: ['draft', 'active', 'paused', 'archived'], required: false },
    },
    outputSchema: { description: '{ service, proposed, change_request }' },
    permission: 'propose',
    risk: 'high',
    allowedPlanes: ['admin'],
    requiredCapabilities: ['services.propose'],
    supportedGrantConstraints: ['channels'],
    sideEffect: 'proposal',
    approvalRequired: true,
    idempotent: true,
    audit: 'proposal_and_execution',
    modelExposed: true,
    serverOnly: false,
    examples: [],
    errorContract: STANDARD_PLATFORM_TOOL_ERRORS,
  }),
]
