import { defineDomain } from './domain-registry'
import { assertValidToolManifest } from './contracts'

/**
 * Reference only. Developers should copy the PATTERN, not this domain.
 * Executable handlers remain source-controlled and are wired separately.
 */
export const EXAMPLE_PAYMENTS_DOMAIN = defineDomain({
  key: 'payments',
  version: 1,
  title: 'Payments',
  description: 'Reference extension module demonstrating a read + proposal + deterministic executor contract.',
  capabilities: ['payments.read', 'payments.propose'],
  tools: [
    assertValidToolManifest({
      key: 'payments.get_status',
      version: 1,
      domain: 'payments',
      title: 'Get payment status',
      description: 'Read the status of a payment visible to the current account.',
      purpose: 'Answer payment-status questions without mutating business data.',
      whenToUse: ['A customer or admin asks for the status of a known payment reference.'],
      whenNotToUse: ['The request is to create, refund, reverse, or edit a payment.'],
      inputSchema: { type: 'object', additionalProperties: false },
      outputSchema: { type: 'object' },
      permission: 'read',
      risk: 'read',
      allowedPlanes: ['customer', 'admin'],
      requiredCapabilities: ['payments.read'],
      supportedGrantConstraints: ['channels'],
      sideEffect: 'none',
      approvalRequired: false,
      idempotent: true,
      audit: 'invocation',
      modelExposed: true,
      serverOnly: false,
      examples: [{ situation: 'Status inquiry', input: { reference: 'PAY-123' }, expectedBehavior: 'Return a customer-safe status.' }],
      errorContract: [{ code: 'NOT_FOUND', safeToShow: true, meaning: 'No visible payment matched the reference.' }],
    }),
    assertValidToolManifest({
      key: 'payments.propose_refund',
      version: 1,
      domain: 'payments',
      title: 'Propose payment refund',
      description: 'Create a typed refund change request; does not refund directly.',
      purpose: 'Collect an admin-authorized refund proposal for deterministic execution after approval.',
      whenToUse: ['A verified admin explicitly requests a refund.'],
      whenNotToUse: ['A customer asks for a refund; record/escalate their request instead of creating an admin mutation.'],
      inputSchema: { type: 'object', additionalProperties: false },
      outputSchema: { type: 'object' },
      permission: 'propose',
      risk: 'high',
      allowedPlanes: ['admin'],
      requiredCapabilities: ['payments.propose'],
      supportedGrantConstraints: ['channels', 'max_amount'],
      sideEffect: 'proposal',
      approvalRequired: true,
      idempotent: true,
      audit: 'proposal_and_execution',
      modelExposed: true,
      serverOnly: false,
      examples: [{ situation: 'Admin requests refund', input: { payment_id: 'uuid', amount: '10.00' }, expectedBehavior: 'Create a typed change request and return its reference.' }],
      errorContract: [{ code: 'STALE_PAYMENT', safeToShow: true, meaning: 'Payment state changed before proposal creation.' }],
    }),
    assertValidToolManifest({
      key: 'payments.execute_refund',
      version: 1,
      domain: 'payments',
      title: 'Execute approved refund',
      description: 'Deterministically applies one approved typed refund change request.',
      purpose: 'Server-only authoritative mutation after approval.',
      whenToUse: ['The change-request worker has atomically claimed an approved refund proposal.'],
      whenNotToUse: ['Never expose this function to a model or accept free-form model arguments.'],
      inputSchema: { type: 'object', additionalProperties: false },
      outputSchema: { type: 'object' },
      permission: 'execute',
      risk: 'critical',
      allowedPlanes: ['admin'],
      requiredCapabilities: ['payments.propose'],
      supportedGrantConstraints: [],
      sideEffect: 'authoritative_write',
      approvalRequired: true,
      idempotent: true,
      audit: 'proposal_and_execution',
      modelExposed: false,
      serverOnly: true,
      examples: [{ situation: 'Worker executes approved CR', input: { change_request_id: 'uuid' }, expectedBehavior: 'Apply exact approved payload once.' }],
      errorContract: [{ code: 'CHANGE_REQUEST_NOT_EXECUTING', safeToShow: false, meaning: 'Executor was invoked outside the claimed CR state.' }],
    }),
  ],
})
